dist: xenial

cache: 
  - pip
  - npm

matrix:
  fast_finish: true
  include:
    - python: "3.7"
      language: python
      cache: pip

    - cache: pip
      os: osx
      osx_image: xcode11.2

addons:
  homebrew:
    update: true
    packages:
      - python

install:
    - pip install -e .[dev]
    - pip install -r requirements.txt
    - pip install -U pytest pytest-cov flake8 codecov
    - yarn

script:
  - make lint
  - make test

after_success:
    - codecov --token 97f16cfc-c334-4401-b4ae-1ed0c6163ade

branches:
  only:
  - master

notifications:
  email: false
